import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <nav
          style={{
            background: "green",
            padding: "20px",
            margin: "0px",
            textAlign: "center",
            textDecoration: "none",
          }}
        >
          <Link style={{ margin: "7px" }} href="/">
            Home
          </Link>
          <Link style={{ margin: "7px" }} href="/posts">
            Posts
          </Link>
          <Link style={{ margin: "7px" }} href="/articles">
            Articles
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
